title: Главная страница.
description: Добро пожаловать! Это главная страница сайта. 
author: Данилов Андрей Викторович.



collections:
  pages:
    output: true
    permalink: "/:name"
  category:
    output: true

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"

# Conversion
markdown: kramdown
highlighter: rouge

# Pagination 
paginate: 10
paginate_path: "/blog/page/:num"

# Plugins
plugins:
  - "jekyll-sitemap"
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
