title: Главная страница.
description: Добро пожаловать! Это главная страница сайта. 
author: Данилов Андрей Викторович.


collections:
  pages:
    output: true
    permalink: "/:name"
  categories:
    output: true
    permalink: "/:collection/:categories"

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Conversion
markdown: kramdown
highlighter: rouge

# Pagination 
paginate: 10
paginate_path: "/blog/page/:num"

# Plugins
plugins:
  - jekyll-paginate
